### ISSUE TITLE
Make protocol pluggable.

### ISSUE THREAD

**Issue by HeinOldewage** [perlin-network/noise#107]
It would be great to be able to make the underlying protocol pluggable. 
This way plugging in a tor layer can give you anonymous peers.

**Comment by iwasaki-kenta** [comment]
By making the underlying protocol pluggable, do you mean specifically being able to switch out the network transport (TCP, UDP, KCP, anything that implemented `net.Conn`)?

If that's the case, that is on our Todo list right now though can easily be done inside `network/network.go`. If more people are looking for it ASAP, we'll make it happen as quickly as possible 😄.

**Comment by iwasaki-kenta** [comment]
Assigning it to @jack0. Goal is to let the network transport layer be modular. Primarily should support only network transport layers in Go that implement the `net.Conn` interface.

**Comment by HeinOldewageRetro** [comment]
@iwasaki-kenta Yes, I was hoping to swap out with something that implements net.Conn. I am glad to see this project having that as one of its goals. I missed the Todo list when looking for if it was one of the goals for this project. Sorry about that.

**Comment by HeinOldewage** [comment]
@iwasaki-kenta Yes, I was hoping to swap out with something that implements net.Conn. I am glad to see this project having that as one of its goals. I missed the Todo list when looking for if it was one of the goals for this project. Sorry about that.

**Comment by gedw99** [comment]
hey @iwasaki-kenta 

yes, I would like to plugin a pure golang webrtc network stack using the webrtc data channels.

here are the two project that are nearing completion:
https://github.com/pions/webrtc
https://github.com/gortc

**Comment by iwasaki-kenta** [comment]
@HeinOldewage @gedw99 Sorry for the late comment, though I just made a PR enabling for custom `net.Conn` and `net.Listener` to be registered into a custom transport layer. This'll enable for integration into new layers such as Tor or WebRTC for example :smile:.
