### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by udnaan** [perlin-network/noise#110]
What exactly is the motivation? After all, TCP itself is decentralized and robust. Cryptography is an addon and HTTP/2 already supports it.

Is there a read up somewhere on the reasoning and the potential applications?

**Comment by iwasaki-kenta** [comment]
Bit of an open-ended question, though would love to speak more to you over on Discord about the intent for Noise.

The rundown however is that Noise primarily works on the application layer of the networking stack for providing a bunch of modular primitives that really greatly assist with creating P2P applications.

On one hand, Noise allows nodes to uniquely have IDs represented as public keys of asymmetric cryptographic key pairs. HTTP/2 does not support this; they support some forms of certification schemes  for the sake of verifying the authenticity of websites under a centralized certificate trust store. HTTP/2 was made to solely cater for the web.

Noise provides you mechanisms to be able to discover other peers in a secure manner (using DHT-based NAT traversal) out of the box. TCP is just* a network transport layer which we see HTTP/2 build on top of, that provides no guidelines or ideas on how exactly it may be used in a P2P networking setting.

If you had to build all the ideas such as node IDs, DHT NAT traversal, and all the little tidbits and security and performance optimizations yourself on top of TCP, or even on top of HTTP/2, you'll be 1) redundantly rewriting code, 2) being easily prone to quite a number of bugs, and 3) as a developer, succumb to reading up on a bunch of papers denoting security guarantees and performance optimizations one has to consider before writing a custom-made P2P networking stack.

Hence, Noise was made to make it really easy for developers to just make P2P apps quick, and to save time to developers by being as minimal of a dependency in letting people plug in the necessary P2P networking and security primitives.
