### ISSUE TITLE
Intermittent Crash (at startup) in Chat App

### ISSUE THREAD

**Issue by faddat** [perlin-network/noise#111]
So... a little bit of background-- I first saw this issue after building the chat example multiplatform using [Gox](https://github.com/mitchellh/gox) after I put the app on a raspberry Pi of mine.  Since then, I've seen it on my mac as well.  

I can't quite make heads or tails of it (I've tried) so I'm filing this issue.  I'm in the discord if you've any questions.  

```
./chat
./chat flag redefined: log_dir
panic: ./chat flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420074060, 0x1292b40, 0xc4200107e0, 0x1269f85, 0x7, 0x12756a5, 0x2f)
	/usr/local/Cellar/go/1.10/libexec/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc420074060, 0xc4200107e0, 0x1269f85, 0x7, 0x0, 0x0, 0x12756a5, 0x2f)
	/usr/local/Cellar/go/1.10/libexec/src/flag/flag.go:713 +0x8b
flag.(*FlagSet).String(0xc420074060, 0x1269f85, 0x7, 0x0, 0x0, 0x12756a5, 0x2f, 0xc4200107d0)
	/usr/local/Cellar/go/1.10/libexec/src/flag/flag.go:726 +0x8b
flag.String(0x1269f85, 0x7, 0x0, 0x0, 0x12756a5, 0x2f, 0x11b3a87)
	/usr/local/Cellar/go/1.10/libexec/src/flag/flag.go:733 +0x69
```

**Comment by faddat** [comment]
broken binaries are here:

https://github.com/galaxypi/chat/releases

**Comment by iwasaki-kenta** [comment]
This usually occurs when you have two different versions of the dependencies `glog` in your app, which conflict with one another upon build.

That's the reason we're using `vgo` which would make use of only one specific version of `glog` for all builds. Try build it using `vgo `build ` and let us know the results.
