### ISSUE TITLE
error: undefined: proto.InternalMessageInfo

### ISSUE THREAD

**Issue by coolmenu** [perlin-network/noise#128]
examples/chat/messages/chat.pb.go:63:33: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:67:24: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:127:29: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:199:26: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:236:26: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:274:39: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:319:40: undefined: proto.InternalMessageInfo
protobuf/stream.pb.go:364:27: undefined: proto.InternalMessageInfo

 protoc --version
libprotoc 3.6.0

**Comment by iwasaki-kenta** [comment]
Is this on `master` branch or using release v1.0?

**Comment by coolmenu** [comment]
when i use vgo get github.com/gogo/protobuf v1.1.1
then have no error

but go.mod : github.com/gogo/protobuf v1.0.0

**Comment by greatbsky** [comment]
you should checkout /perlin-network/noise/tree/v1.0.0, there is no error.
