### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by inceptchain** [perlin-network/noise#136]
I am running into a vgo mod -sync error, that tells me it cannot find:

go: import "github.com/gogo/protobuf/protoc-gen-gogofaster/gocode/src/github.com/golang/mock/mockgen/tests/vendor_dep" ->
	import "a": cannot find module providing package a

I had an issue with protobufs 3.6 not working and versioned down to 3.5.1, that fixed the protobuf issue so maybe there are other versioning issues?

running ubuntu 18.04

**Comment by iwasaki-kenta** [comment]
With the latest Go beta, those issues should not occur anymore. Make sure with the latest Go beta you use change all commands from using `vgo` to `go`.

**Comment by Lucidbitness** [comment]
I have the 1.10.3 go version, is that the correct one that I can use go
rather than vgo?

**Comment by iwasaki-kenta** [comment]
go 1.11+ is the correct one.

**Comment by TanNgocDo** [comment]
Shoud we update from 'vgo' to 'go' in readme ? I was confused for the first time

**Comment by iwasaki-kenta** [comment]
The README has now been updated to help users setup their projects more easily with Go 1.11+.
