### ISSUE TITLE
use UPNP

### ISSUE THREAD

**Issue by pwc5232759** [perlin-network/noise#156]
log：
I0910 11:42:08.731264   15248 main1.go:46] Private Key: 79f92dfe6267bcc95d347a0447408bf57c14fb8781e223e273afedbe5248dd12c3206ae6362428246fea928366b993f66d5ce0d938c50a2b36cb91be280cf148
I0910 11:42:08.738208   15248 main1.go:47] Public Key: c3206ae6362428246fea928366b993f66d5ce0d938c50a2b36cb91be280cf148
I0910 11:42:08.741184   15248 plugin.go:32] Setting up NAT traversal for address: kcp://127.0.0.1:3002
I0910 11:42:10.946909   15248 plugin.go:59] Discovered gateway following the protocol UPNP (IG1-IP1).
I0910 11:42:10.946909   15248 plugin.go:61] Internal IP: 192.168.2.102
I0910 11:42:10.946909   15248 plugin.go:62] External IP: 100.100.149.137
I0910 11:42:11.093523   15248 plugin.go:71] External port 60858 now forwards to your local port 3002.
I0910 11:42:11.093523   15248 plugin.go:82] Other peers may connect to you through the address kcp://100.100.149.137:60858.
I0910 11:42:11.094019   15248 network.go:206] Listening for peers on kcp://100.100.149.137:60858.

Why the External IP is not my public network IP？

**Comment by losfair** [comment]
The external IP is provided by your UPnP gateway. If your gateway is behind a NAT itself, it is impossible to get the real public IP since we do not want to rely on any centralized service.
