### ISSUE TITLE
Connect Bug 

### ISSUE THREAD

**Issue by pwc5232759** [perlin-network/noise#157]
I did an experiment：
1：I ran chat/main.go on the public network.
2：I also ran chat/main.go on my local intranet.

The intranet takes the initiative to connect to the public network.
and connect failure

log：
1：public network：
I0914 15:35:59.067335    5092 main.go:45] Private Key: e1c79968020ee18a725849826e7130c4bb9e4962d255b6829fd8ab64534658f85640464458ddeef9eeb93368779c7015a2a43ff374ff23b3eae23b47dbfb75e8
I0914 15:35:59.067392    5092 main.go:46] Public Key: 5640464458ddeef9eeb93368779c7015a2a43ff374ff23b3eae23b47dbfb75e8
I0914 15:35:59.067700    5092 network.go:206] Listening for peers on tcp://47.91.166.18:3001.
E0914 15:38:06.366141    5092 network.go:319] dial tcp 183.192.11.228:3000: connect: connection timed out

2：local intranet：
I0914 15:36:05.452905   21932 main.go:46] Private Key: 31d4fefef611b233374a1b99363eb55dd0919b383108911bc909f455de22af0d425efc07c0d7d68d203d0e3ea1c8702a2968dd3d16f34a3909648520ade5c91d
I0914 15:36:05.459852   21932 main.go:47] Public Key: 425efc07c0d7d68d203d0e3ea1c8702a2968dd3d16f34a3909648520ade5c91d
I0914 15:36:05.464287   21932 network.go:206] Listening for peers on tcp://127.0.0.1:3000.

I think the port of public network connect local intranet should‘t be 3000 ，is right？

forgive my poor English

**Comment by iwasaki-kenta** [comment]
Options have been provided when using NAT traversal to be able to specify the internal/external ports to use, alongside the external address to broadcast to other peers for Noise v2.0.
