### ISSUE TITLE
When a client is left for a long period of time, flushing the loop fails

### ISSUE THREAD

**Issue by alex-godwin** [perlin-network/noise#163]
After leaving a peer for a long period (in our case a day or so) the error below is rapidly logged.
`W1004 15:11:53.124320   14174 network.go:114] i/o timeout` 

Looks like it comes from this block:
```golang
if err := state.writer.Flush(); err != nil {
   log.Warn().Err(err).Msg("")
}

```

**Comment by iwasaki-kenta** [comment]
Noise v2.0 removes recv/send buffering, and randomly handles it using channels instead.

There should no longer be an issue with flushing in spite of a client being left for a long period of time.
