### ISSUE TITLE
possible to use when a member cannot be dialed?

### ISSUE THREAD

**Issue by tobowers** [perlin-network/noise#169]
Hi! 

I'm trying to determine if Noise can be used when a member of the p2p network cannot be dialed. I was experimenting using docker where host B can dial host A, but host A cannot dial host B. 

I tried to have host B bootstrap to A, but then it appears that A tries to dial B and it fails... it doesn't look like a bi-directional connection is setup.

Is that true?

My use-case is for clients to connect to the network where the built-in NAT busting doesn't work, but we could establish relays (similar to your proxy example) to get messages to the clients.

**Comment by jack0** [comment]
If you are using v1.1.0 release, it isn't using bi-directional but two sockets for each pair of peers. If you use master right now commit `e83afc3` it uses a single connection between peers. Try that and see if it works. There are some breaking changes though in master from the previous v1.1.0 release such as registering your protobuf message.

**Comment by tobowers** [comment]
Looks like (from the code) that this is better. Thanks! Here's some code I'm playing with: https://github.com/QuorumControl/noiseplay

specifically: https://github.com/QuorumControl/noiseplay/tree/master/natter

And the docker compose to simulate undialable client: https://github.com/QuorumControl/noiseplay/blob/master/docker-compose.yml

Now I'm getting the error "network: sender address did not match connection remote address" from here: https://github.com/perlin-network/noise/blob/master/network/network.go#L290

The concept of address here seems too tied to the actual dialable internet address for a p2p network (imho). If I can't get my external IP from the NAT plugin, then I can't connect to the network... even though I'm routable (given the new connection handling).

I'd actually be happy to contribute some code here, but architecturally it seems like the internal code seems to think of "address" as dialable.

**Comment by jack0** [comment]
@tobowers yes this is an issue we need to fix. feel free to open a PR for this, thanks!

**Comment by iwasaki-kenta** [comment]
The issue has been addressed and solved with Noise v2.

Manually setting a `Host` will stop Noise from querying the router via some NAT traversal plugin to get your external address.
