### ISSUE TITLE
kcp error on examples/chat

### ISSUE THREAD

**Issue by hjlp20150803** [perlin-network/noise#171]
when I blank protocol it's fine, when use protocol=kcp, error reported:
xxxx$ go run main.go -host=192.168.1.102 -peers=kcp://192.168.1.104:3000 -protocol=kcp
2018-10-20T18:28:21+08:00 |WARN| caller=/Users/xxxx/go/src/github.com/perlin-network/noise/network/network.go:116 error="broken pipe"

one more thing, when peer on win10, it exit; ok under macOS and ubuntu

**Comment by jack0** [comment]
what commit are you testing this on?

**Comment by hjlp20150803** [comment]
xxx:noise xxx$ git log
commit e83afc330dff8ababf2e4915adb52de60ed7beec (HEAD -> master, origin/master, origin/HEAD)
Author: Jack <jack0@users.noreply.github.com>
Date:   Tue Oct 16 11:53:00 2018 -0400

**Comment by iwasaki-kenta** [comment]
KCP will be removed for Noise v2.
