### ISSUE TITLE
Which version of noise should we use?

### ISSUE THREAD

**Issue by guyu96** [perlin-network/noise#199]
We would like to use noise in our p2p application, and we noticed that there is a v2 branch. Could you tell us whether we should use the master branch, the latest release (v1.1), or the v2 branch?

**Comment by iwasaki-kenta** [comment]
The latest release (v1.1) is highly recommended to be used.

All code in `v2` is currently a work in progress (although near completion) which represents a significant refactor we are releasing soon addressing a large number of RFCs users have made while trying out Noise.

If you're interested in experimenting with the new `v2` API from the get-go though, feel free to try it out although documentation is still in the works.

Basic v2 Chat Example: https://github.com/perlin-network/noise/tree/v2/examples/chat

**Comment by guyu96** [comment]
Thank you! Is there an expected release date for `v2`?

**Comment by iwasaki-kenta** [comment]
> Thank you! Is there an expected release date for `v2`?

Within the next coming week :smile:.

**Comment by guyu96** [comment]
Can't wait. Thanks Kenta!

**Comment by iwasaki-kenta** [comment]
Noise v2.0 is out now :smile:.

Release notes: https://github.com/perlin-network/noise/releases/tag/v2.0.0
Documentation: https://perlin-network.github.io/noise/
