### ISSUE TITLE
How do i use UPNP instead of NAT_PMP?

### ISSUE THREAD

**Issue by siredwin** [perlin-network/noise#204]
Great package.

Everything works good but port-forwarding using nat-pmp is not working.
Everything works fine when I do my own port forwarding using UPNP IGDP.

Most NAT routers use UPNP. I think that should be the default mode of port-forwarding.

**Comment by iwasaki-kenta** [comment]
UPnP IGDPv2 and IDGPv3 alongside NAT-PMP are now 100% supported in Noise v2.0.

https://perlin-network.github.io/noise/nat.html

Please do try it out and let me know how it works out for you.
