### ISSUE TITLE
Question about service discovery

### ISSUE THREAD

**Issue by bbalet** [perlin-network/noise#211]
Hi,

Sorry to bother you with this question. Actually I am not sure if your library can be used for my scenario. My scenario is quite simple, I want to detect all computer running my service on a local network. A bit like UPnP/AV that are able to discover media servers on the network.

So I've tried your examples (e.g. the chat) but in my scenario I just want to list the peers (their IP addresses) at the moment, I don't want to connect to them. So I got rid of everything related to messaging and Dial from the code. But then `skademlia.FindNode(...)` returns an empty array. In your example, it looks like you know in advance that a peer would run on localhost so you can connect to it, you don't discover it.

**Comment by iwasaki-kenta** [comment]
At the moment, S/Kademlia discovers peers within your network by recursively walking through all neighboring nodes you know about.

Hence, inevitably your node in some way has to dial at least log(n) peers to know all of the peers within the network. The same goes for any other peer discovery-based solution.

If it's a matter of wishing to get rid of the peers connections after discovering them, then it is a matter of keeping the code entirely the same, and after calling `FindNode(..)`, you'd disconnect from all of your peers by calling `peer.Disconnect()`.

You can alternatively kill your node by calling `node.Kill()` and simply print out all peers discovered in your routing table by calling `skademlia.Table(node).GetPeers()`.

**Comment by iwasaki-kenta** [comment]
Should you wish to have your devices discover each other over a local network, a centralized approach would work too where you'd just have one node be responsible for keeping track of all devices and their status.

Any device can then send a message to this central node to get a list of all available peers.

**Comment by schuerg** [comment]
You could use *mDNS-SD (multicast DNS Service Discovery)* to discover all nodes on your local network. mDNS is also sometimes referred to as *Zeroconf*. In my experience, this works quite easy and reliably in local IP networks.

There are [several implementations for Go](https://libs.garden/go/search?q=zeroconf%20mdns&sort=popular).

- [Wikipedia - DNS-SD with multicast](https://en.wikipedia.org/wiki/Zero-configuration_networking#DNS-SD_with_multicast)
- [RFC 6762 - Multicast DNS](https://tools.ietf.org/html/rfc6762)
- [RFC 6763 - DNS-Based Service Discovery](https://tools.ietf.org/html/rfc6763)
- [Avahi](http://avahi.org/): A free Zeroconf / mDNS-SD implementation, which is used on most Linux systems today

Using *mDNS-SD* together with *perlin-network/noise* enables you to bootstrap peer2peer connections on the local network without specifying initial bootstrap nodes manually.

**Comment by bbalet** [comment]
Thanks for your precious inputs. I guess we can close this issue.
