### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by bittelc** [perlin-network/noise#216]
Hello,

Since the initial [blog plost](https://medium.com/perlin-network/noise-an-opinionated-p2p-networking-stack-for-decentralized-protocols-in-go-bfc6fecf157d) that brought a lot of attention to Noise, there's been little updates on what's happening with the project, what the priorities are for roadmap (tags `v1.0.0`, `v1.1.0`, and `v2.0.0` are equally ambiguous), and how to actually the use Noise as a networking stack in external apps.

We've attempted to use Noise in our own apps but we've run into lots of problems with implementation, particularly because there is very little documentation available. The `examples` directory seems to be a state of flux, as it no longer represents very accurately what was initially published on the blog post.

I would love to see better documentation and goals of upcoming development.

**Comment by iwasaki-kenta** [comment]
More complete godocs alongside examples are being provided in the next update #266. Also, Noise from then on will make use of semantic versioning. I echo a lot of the concerns regarding the present versioning system of Noise, and hope the update ceases these problems.
