### ISSUE TITLE
how can i get all peers ip?

### ISSUE THREAD

**Issue by ystyle** [perlin-network/noise#219]
i found this: 
```go
skademlia.Table(node).GetPeers()
```
but all my peers run in docker, it return all ip is 127.0.0.1

have an api return []noise.Peer ?

**Comment by iwasaki-kenta** [comment]
Please refer to the `cleanup` branch in the mean time for the latest version. To get all peers connected to you, use `(*skademlia.Client).ClosestPeers()` or `(*skademlia.Client).AllPeers()` .

**Comment by ystyle** [comment]
Will the cleanup branch be 3.0?

**Comment by iwasaki-kenta** [comment]
> Will the cleanup branch be 3.0?

It will specifically be 2.0. The release will be coming soon.

**Comment by rkeene** [comment]
@ystyle Did this resolve your issue ?

It might also be significant to note that the "127.0.0.1" is going to be the address the peer indicated was its own address which leads me to believe there is an additional issue with the usage.
