### ISSUE TITLE
Better strategy for selecting peers in case of failed connection

### ISSUE THREAD

**Issue by a-urth** [perlin-network/noise#224]
Currently there are same peers selected and tried to dial even in case they failed recently. Which results to huge delay (especially in case of default 3s connection timeout).

There should be better strategy which should consider latest successful/failed connection to select only live (or potentially live) peers.

**Comment by a-urth** [comment]
As possible solution - since noise is grpc based now, we can utilize grpc health check and "ping" peers from time to time and mark them [in]active.

**Comment by iwasaki-kenta** [comment]
Just to be sure, what if a peer responds ASAP for health check requests but intentionally delays any other response messages?

**Comment by a-urth** [comment]
Timeout still should be a thing. you are talking now about "bad" peer and i'm about peers which is legit but just shut down or has network issues

**Comment by iwasaki-kenta** [comment]
> Timeout still should be a thing. you are talking now about "bad" peer and i'm about peers which is legit but just shut down or has network issues

Of course, want to make sure that a bad peer does not falter the health check. The timeouts that should be set for a health check request should be the same for dial timeouts, and alternative RPC timeouts.

**Comment by a-urth** [comment]
IMO timeout for healthcheck should be smaller than for any other rpc call. since it involves no cpu, its just pure networking latency. and if peer cannot respond to health check in time its highly likely that it won't be able to respond to any proper rpc call.

**Comment by rkeene** [comment]
See also #242
