### ISSUE TITLE
Can messages be inspected before deciding to relay them?

### ISSUE THREAD

**Issue by SentRaise** [perlin-network/noise#230]
Suppose a node is sending properly formed but ultimately invalid information over the network.

Is there any way for each node to inspect a message before relaying it to discriminate against (spam/irrelevant) messages?

An example would be if someone was attempting to spend Bitcoin that doesn't exist. It would be counterproductive for the whole network to see that message if individual nodes originally receiving it could have muted them.

**Comment by iwasaki-kenta** [comment]
Yes, it is possible. Relays have yet to be implemented however.
