### ISSUE TITLE
MasterPeerNode

### ISSUE THREAD

**Issue by Lisahobe1998** [perlin-network/noise#238]
Does Perlin Noise need a MasterPeerNode to find other Peers?

**Comment by rkeene** [comment]
A node may connect to any peer to be introduced to the network.  Usually, for nodes which have not connected to a network before and need an introduction networks will provide a peer at a well-known address.

Is that what you are asking about ?

**Comment by iwasaki-kenta** [comment]
Peer discovery requires a few select bootstrap/seed nodes to interact with that may be trusted.

**Comment by jinxmcg** [comment]
> for nodes which have not connected to a network before and need an introduction networks will provide a peer at a well-known address.

How do you specify the "well-known address" or "few select bootstrap/seed nodes" ? I have this use case. How would this look in the chat example?

Thank you

**Comment by jinxmcg** [comment]
I just found it in the source code. No need to answer thank you.
