### ISSUE TITLE
Update skademlia.DisconnectByAddress to remove unconnected nodes

### ISSUE THREAD

**Issue by rkeene** [perlin-network/noise#243]
Currently if you call `skademlia.DisconnectByAddress()` on address that could not be successfully connected to, it does not remove it from the list of all peers -- which comes from `(*skademlia.Client).AllPeers`, which only consults the local map.

Subsequent calls to `(*skademlia.Table).FindClosest` still find the broken connection in the table/bucket.

**Comment by iwasaki-kenta** [comment]
Connections are now pooled on #266, and therefore this is no longer an issue.
