### ISSUE TITLE
Dependency github.com/adl/ed25519 no longer maintained and available

### ISSUE THREAD

**Issue by DavidMinarsch** [perlin-network/noise#278]
Executing `go get -u github.com/perlin-network/noise` causes:
```
package github.com/agl/ed25519/extra25519: cannot find package "github.com/agl/ed25519/extra25519" in any of:
	/usr/local/go/src/github.com/agl/ed25519/extra25519 (from $GOROOT)
	/Users/{user}/go/src/github.com/agl/ed25519/extra25519 (from $GOPATH)
```

Looking at https://github.com/agl/ed25519 it appears the commit [9517982](https://github.com/agl/ed25519/commit/95179825112d23b5f3936e9e864f265c6242c092) from 5 days ago removed the code and points the user towards [x/crypto/ed25519](https://godoc.org/golang.org/x/crypto/ed25519).

**Comment by alawik** [comment]
I got the same error. Looks like the [ecdh.go](https://github.com/perlin-network/noise/blob/master/ecdh.go) file will have to be edited.

**Comment by iwasaki-kenta** [comment]
Thank you! Fixed it and will publish an updated version.

https://github.com/perlin-network/noise/commit/a2ae1d2f9141e9690e0e8eaac5ce84f0098c9cda
