### ISSUE TITLE
Create proxying example.

### ISSUE THREAD

**Issue by iwasaki-kenta** [perlin-network/noise#48]
Of course, the main goal is to make examples as intuitive as possible. We should all try out different examples to illustrate that it's relatively easy to use Noise with a minimal number of LoC.

This example constitutes of proxying messages from one node to another.

## Steps
1. We have Node 0, 1, 2.
2. Nodes 1, 2 will bootstrap with Node 0.
3. Node 0 will send a message to Node 1.
4. Node 1 will proxy the message to Node 2.
5. Node 2 will print out that they received the message.

## Style Reference

Please refer to the comment styling and example directory format for the `basic` example located here: https://github.com/perlin-network/noise/tree/master/examples/basic

**Comment by creamwhip** [comment]
I realise that this is an old issue, but I'm trying out the `cleanup` branch and would like to know whether there is a new solution for proxying messages through to all peers in the network.

I've noticed the `ClosestPeers()` and `AllPeers()` methods on `*skademlia.Client` but these appear to only send messages to the connected peers.

Must this be handled by application logic?

Thank you!

**Comment by notatestuser** [comment]
^ Sorry, I'm not sure how that happened.
